fix git fetch in git-updater in redmine - closes #112
Signed-off-by: Marcin Fabrykowski <git@fabrykowski.pl>

diff --git a/chart/templates/redmine/redmine.yml b/chart/templates/redmine/redmine.yml
--- a/chart/templates/redmine/redmine.yml
+++ b/chart/templates/redmine/redmine.yml
@@ -58,7 +58,7 @@ spec:
                   yq e -o=json  /configmaps/repos |jq -r '.[] | [.name, .repo] | @tsv' > /tmp/repos.txt;
                   while IFS=$'\t' read -r name repo _; do
                     echo processing \"$repo\" \"$name\";
-                    [ -d $name ] && (echo 'found. updating'; cd \"$name\"; git fetch)||(echo 'not found. clonning'; git clone --bare \"$repo\" \"$name\")
+                    [ -d $name ] && (echo 'found. updating'; cd \"$name\"; git fetch origin master:master)||(echo 'not found. clonning'; git clone --bare \"$repo\" \"$name\")
                   done </tmp/repos.txt;
                   [ -e /configmaps/ws ] && curl localhost:3000/sys/fetch_changesets?key=$(cat /configmaps/ws);
                   sleep 60;
